In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Read the dataset to python environment
data=pd.read_csv('loan_dataset.csv')

In [3]:
data.head()

loan_id source       financial_institution  interest_rate  \
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250   
1  672831657627      Y  Swanson, Newton and Miller          4.875   
2  742515242108      Z              Thornton-Davis          3.250   
3  601385667462      X                       OTHER          4.750   
4  273870029961      X                       OTHER          4.750   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                214000        360       2012-03-01            05/2012   
1                144000        360       2012-01-01            03/2012   
2                366000        180       2012-01-01            03/2012   
3                135000        360       2012-02-01            04/2012   
4                124000        360       2012-02-01            04/2012   

   loan_to_value  number_of_borrowers  ...  m4  m5 m6  m7  m8  m9  m10  m11  \
0             95                  1.0  ...   0   0  0   1   0   0    0    0   
1             72                  1.0  ...   0   0  0   0   0   0    0    1   
2             49                  1.0  ...   0   0  0   0   0   0    0    0   
3             46                  2.0  ...   0   0  0   0   0   1    1    1   
4             80                  1.0  ...   3   4  5   6   7   8    9   10   

   m12  m13  
0    0    1  
1    0    1  
2    0    1  
3    1    1  
4   11    1  

[5 rows x 29 columns]

In [4]:
# Checking the number of rows and columns
data.shape

(116058, 29)

In [5]:
#Checking for unique values in each column
data.nunique()

loan_id                     116058
source                           3
financial_institution           19
interest_rate                  923
unpaid_principal_bal           646
loan_term                      140
origination_date                 3
first_payment_date               4
loan_to_value                   92
number_of_borrowers              2
debt_to_income_ratio            58
borrower_credit_score          221
loan_purpose                     3
insurance_percent               14
co-borrower_credit_score       216
insurance_type                   2
m1                               4
m2                               5
m3                               6
m4                               7
m5                               8
m6                               9
m7                              10
m8                              10
m9                              11
m10                             12
m11                             13
m12                             13
m13                 

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116058 entries, 0 to 116057
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   loan_id                   116058 non-null  int64  
 1   source                    116058 non-null  object 
 2   financial_institution     116058 non-null  object 
 3   interest_rate             116058 non-null  float64
 4   unpaid_principal_bal      116058 non-null  int64  
 5   loan_term                 116058 non-null  int64  
 6   origination_date          116058 non-null  object 
 7   first_payment_date        116058 non-null  object 
 8   loan_to_value             116058 non-null  int64  
 9   number_of_borrowers       116058 non-null  float64
 10  debt_to_income_ratio      116058 non-null  float64
 11  borrower_credit_score     116058 non-null  float64
 12  loan_purpose              116058 non-null  object 
 13  insurance_percent         116058 non-null  f

In [7]:
#removing the unwanted columns
data1=data.drop(['loan_id','source','financial_institution','loan_purpose','origination_date','first_payment_date','number_of_borrowers'],axis=1)

In [8]:
data1.head()

interest_rate  unpaid_principal_bal  loan_term  loan_to_value  \
0          4.250                214000        360             95   
1          4.875                144000        360             72   
2          3.250                366000        180             49   
3          4.750                135000        360             46   
4          4.750                124000        360             80   

   debt_to_income_ratio  borrower_credit_score  insurance_percent  \
0                  22.0                  694.0               30.0   
1                  44.0                  697.0                0.0   
2                  33.0                  780.0                0.0   
3                  44.0                  633.0                0.0   
4                  43.0                  681.0                0.0   

   co-borrower_credit_score  insurance_type  m1  ...  m4  m5  m6  m7  m8  m9  \
0                       0.0             0.0   0  ...   0   0   0   1   0   0   
1                       0.0             0.0   0  ...   0   0   0   0   0   0   
2                       0.0             0.0   0  ...   0   0   0   0   0   0   
3                     638.0             0.0   0  ...   0   0   0   0   0   1   
4                       0.0             0.0   0  ...   3   4   5   6   7   8   

   m10  m11  m12  m13  
0    0    0    0    1  
1    0    1    0    1  
2    0    0    0    1  
3    1    1    1    1  
4    9   10   11    1  

[5 rows x 22 columns]

In [9]:
data1.isna().sum()

interest_rate               0
unpaid_principal_bal        0
loan_term                   0
loan_to_value               0
debt_to_income_ratio        0
borrower_credit_score       0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
m1                          0
m2                          0
m3                          0
m4                          0
m5                          0
m6                          0
m7                          0
m8                          0
m9                          0
m10                         0
m11                         0
m12                         0
m13                         0
dtype: int64

In [10]:
# Seperating the data into dependent and independent variables.
X=data1.drop('m13',axis=1)
y=data1['m13']

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## 1. Logistic Regression

In [13]:
#importing the libraries for logistic regression
from sklearn.linear_model import LogisticRegression

In [14]:
# Instantiate learning model
log_reg=LogisticRegression()

In [15]:
# Fitting the model
log_reg_model=log_reg.fit(X_train,y_train)
# Predicting the Test set results
log_reg_pred=log_reg_model.predict(X_test)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
#Evaluating Predictions
from sklearn.metrics import confusion_matrix

In [17]:
# Confusion Matrix
confusion_matrix(y_test,log_reg_pred)

array([[23073,    11],
       [  128,     0]], dtype=int64)

In [18]:
# accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,log_reg_pred)

0.9940117180768568

In [19]:
#precision score,recall score
from sklearn.metrics import precision_score,recall_score

In [20]:
precision_score(y_test,log_reg_pred)

0.0

In [49]:
recall_score(y_test,log_reg_pred)

0.3203125

## 2. Support Vector Machine

In [21]:
# Importing libraries for SVM model
from sklearn.svm import SVC

In [22]:
# SVM with RBF kernel
svm_clf=SVC(kernel='rbf')
svm_model=svm_clf.fit(X_train,y_train)
svm_pred=svm_model.predict(X_test)

In [23]:
#Evaluating Predictions
# Confusion Matrix

In [24]:
confusion_matrix(y_test,svm_pred)

array([[23084,     0],
       [  128,     0]], dtype=int64)

In [25]:
# accuracy score
accuracy_score(y_test,svm_pred)

0.9944856108909185

## 3. Decision Tree Classifier

In [26]:
# importing libraries for decision tree classifier

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
# Instantiate learning model
dt_clf=DecisionTreeClassifier()
# Fitting the model
dt_clf=dt_clf.fit(X_train,y_train)
# Predicting the Test set results
y_pred_dt=dt_clf.predict(X_test)

Evaluating Predictions

In [29]:
# Confusion Matrix
confusion_matrix(y_test,y_pred_dt)

array([[22997,    87],
       [   80,    48]], dtype=int64)

In [30]:
# Accuracy Score
accuracy_score(y_test,y_pred_dt)

0.9928054454592452

## 4. Random Forest Algorithm

In [31]:
# importing libraries for random forest algorithm

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
# Instantiate learning model
rf_clf=RandomForestClassifier()
# Fitting the model
rf_clf=rf_clf.fit(X_train,y_train)
# Predicting the Test set results
y_pred_rf=rf_clf.predict(X_test)

Evaluating Predictions

In [34]:
# Confusion Matrix
confusion_matrix(y_test,y_pred_rf)

array([[23068,    16],
       [   84,    44]], dtype=int64)

In [35]:
# Accuracy Score
accuracy_score(y_test,y_pred_rf)

0.9956918835085301

## Standard Scaling

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
std_scl=StandardScaler()

In [38]:
X.iloc[:] = std_scl.fit_transform(X.iloc[:])

In [40]:
X.describe()

interest_rate  unpaid_principal_bal     loan_term  loan_to_value  \
count   1.160580e+05          1.160580e+05  1.160580e+05   1.160580e+05   
mean    4.469170e-16         -5.671026e-17  3.339967e-16  -6.726426e-16   
std     1.000004e+00          1.000004e+00  1.000004e+00   1.000004e+00   
min    -3.511708e+00         -1.719727e+00 -2.587742e+00  -3.552695e+00   
25%    -8.003173e-01         -7.692944e-01 -1.250874e+00  -6.032936e-01   
50%     1.309988e-02         -2.199617e-01  7.544282e-01   2.641773e-01   
75%     5.553780e-01          6.083971e-01  7.544282e-01   7.268285e-01   
max     6.249298e+00          8.647837e+00  7.544282e-01   1.709962e+00   

       debt_to_income_ratio  borrower_credit_score  insurance_percent  \
count          1.160580e+05           1.160580e+05       1.160580e+05   
mean          -4.558249e-17           1.053441e-15      -1.194079e-15   
std            1.000004e+00           1.000004e+00       1.000004e+00   
min           -3.056524e+00          -1.824016e+01      -3.441379e-01   
25%           -7.956517e-01          -4.483900e-01      -3.441379e-01   
50%            2.648380e-02           2.860240e-01      -3.441379e-01   
75%            8.486193e-01           7.124579e-01      -3.441379e-01   
max            3.417793e+00           1.660089e+00       4.596312e+00   

       co-borrower_credit_score  insurance_type            m1  ...  \
count              1.160580e+05    1.160580e+05  1.160580e+05  ...   
mean              -7.461141e-15    1.412815e-15 -5.397938e-15  ...   
std                1.000004e+00    1.000004e+00  1.000004e+00  ...   
min               -1.203344e+00   -5.716323e-02 -5.045801e-02  ...   
25%               -1.203344e+00   -5.716323e-02 -5.045801e-02  ...   
50%                7.341063e-01   -5.716323e-02 -5.045801e-02  ...   
75%                8.676333e-01   -5.716323e-02 -5.045801e-02  ...   
max                9.854512e-01    1.749376e+01  4.730309e+01  ...   

                 m3            m4            m5            m6            m7  \
count  1.160580e+05  1.160580e+05  1.160580e+05  1.160580e+05  1.160580e+05   
mean  -7.020845e-15 -3.962017e-14 -1.266139e-14  5.294998e-14 -1.289509e-14   
std    1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00   
min   -3.559909e-02 -3.506927e-02 -4.274965e-02 -3.907017e-02 -4.122105e-02   
25%   -3.559909e-02 -3.506927e-02 -4.274965e-02 -3.907017e-02 -4.122105e-02   
50%   -3.559909e-02 -3.506927e-02 -4.274965e-02 -3.907017e-02 -4.122105e-02   
75%   -3.559909e-02 -3.506927e-02 -4.274965e-02 -3.907017e-02 -4.122105e-02   
max    9.017311e+01  9.648831e+01  8.466474e+01  9.133435e+01  8.910225e+01   

                 m8            m9           m10           m11           m12  
count  1.160580e+05  1.160580e+05  1.160580e+05  1.160580e+05  1.160580e+05  
mean  -3.712566e-14 -2.005542e-14 -1.414341e-14  4.808151e-15 -4.810822e-14  
std    1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  
min   -4.265242e-02 -4.179149e-02 -4.458259e-02 -4.364174e-02 -4.527618e-02  
25%   -4.265242e-02 -4.179149e-02 -4.458259e-02 -4.364174e-02 -4.527618e-02  
50%   -4.265242e-02 -4.179149e-02 -4.458259e-02 -4.364174e-02 -4.527618e-02  
75%   -4.265242e-02 -4.179149e-02 -4.458259e-02 -4.364174e-02 -4.527618e-02  
max    8.835297e+01  8.573409e+01  8.080176e+01  7.976805e+01  7.855011e+01  

[8 rows x 21 columns]

## Logistic Regression after Standard Scaling

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
# Instantiate learning model
log_reg=LogisticRegression()

In [43]:
# Fitting the model
log_reg_model=log_reg.fit(X_train,y_train)
# Predicting the Test set results
log_reg_pred=log_reg_model.predict(X_test)

In [44]:
# Confusion Matrix
confusion_matrix(y_test,log_reg_pred)

array([[23081,     3],
       [   87,    41]], dtype=int64)

In [45]:
# accuracy score
accuracy_score(y_test,log_reg_pred)

0.996122695157677

In [46]:
#precision score,recall score

In [47]:
precision_score(y_test,log_reg_pred)

0.9318181818181818

In [48]:
recall_score(y_test,log_reg_pred)

0.3203125

## SVM after Scaling

In [50]:
# SVM with RBF kernel
svm_clf=SVC(kernel='rbf')
svm_model=svm_clf.fit(X_train,y_train)
svm_pred=svm_model.predict(X_test)

In [51]:
#Evaluating Predictions
# Confusion Matrix

In [52]:
confusion_matrix(y_test,svm_pred)

array([[23079,     5],
       [  114,    14]], dtype=int64)

In [53]:
# accuracy score
accuracy_score(y_test,svm_pred)

0.9948733413751508

## Decision Tree

In [54]:
# Instantiate learning model
dt_clf=DecisionTreeClassifier()
# Fitting the model
dt_clf=dt_clf.fit(X_train,y_train)
# Predicting the Test set results
y_pred_dt=dt_clf.predict(X_test)

In [55]:
# Confusion Matrix
confusion_matrix(y_test,y_pred_dt)

array([[23001,    83],
       [   82,    46]], dtype=int64)

In [56]:
# Accuracy Score
accuracy_score(y_test,y_pred_dt)

0.9928916077890746

## Random forest

In [57]:
# Instantiate learning model
rf_clf=RandomForestClassifier()
# Fitting the model
rf_clf=rf_clf.fit(X_train,y_train)
# Predicting the Test set results
y_pred_rf=rf_clf.predict(X_test)

In [58]:
# Confusion Matrix
confusion_matrix(y_test,y_pred_rf)

array([[23071,    13],
       [   83,    45]], dtype=int64)

In [59]:
# Accuracy Score
accuracy_score(y_test,y_pred_rf)

0.9958642081681889

After Scaling Accuracy improved for logistic regression.